"""corrected

Revision ID: 06d8a44f1136
Revises: 49b7de5d5f88
Create Date: 2023-07-20 13:42:48.197162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06d8a44f1136'
down_revision = '49b7de5d5f88'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'topics', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'topics', type_='foreignkey')
    op.drop_column('topics', 'user_id')
    # ### end Alembic commands ###
