"""Added required tables

Revision ID: 080330d1dc98
Revises: 9e105e6eaf8d
Create Date: 2023-07-17 22:10:22.337669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '080330d1dc98'
down_revision = '9e105e6eaf8d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
