"""corrected

Revision ID: 0fe94d7388fa
Revises: 06d8a44f1136
Create Date: 2023-07-20 17:38:03.756888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fe94d7388fa'
down_revision = '06d8a44f1136'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
