"""Added required tables

Revision ID: 9e105e6eaf8d
Revises: 1ecba027f8f5
Create Date: 2023-07-17 20:40:28.236820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e105e6eaf8d'
down_revision = '1ecba027f8f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
